# If you don't know what this does, please don't modify this!
# https://minecraft.wiki/w/Java_Edition_protocol/Entity_metadata#Living_Entity
DATA_EFFECT_PARTICLES=10
DATA_ARROW_COUNT_ID=12
DATA_STINGER_COUNT_ID=13
# https://minecraft.wiki/w/Java_Edition_protocol/Entity_metadata#Entity
DATA_SHARED_FLAGS_ID=0
BIT_MAP_FIRE=1