# Hide items in mainhand?
mainhand=true
# Hide items in offhand?
offhand=true
# Hide boots?
boots=true
# Hide leggings?
leggings=true
# Hide chestplate?
chestplate=true
# Hide helmet?
helmet=true
# Hide animals' armor?
body=true
# Hide effect DATA_EFFECT_PARTICLES?
particles=true
# Hide DATA_ARROW_COUNT_ID in body?
arrows=true
# Hide DATA_STINGER_COUNT_ID in body?
stingers=true
# Hide BIT_MAP_FIRE in body?
fire=true