# Hide items in mainhand?
mainhand=true
# Hide items in offhand?
offhand=true
# Hide boots?
boots=true
# Hide leggings?
leggings=true
# Hide chestplate?
chestplate=true
# Hide helmet?
helmet=true
# Hide animals' armor?
body=true
# Hide effect particles?
particles=true
# Hide arrows in body?
arrows=true
# Hide stingers in body?
stingers=true
# Hide fire in body?
fire=true