name: RealInvisibility
author: '557'
version: '${version}'
website: 'https://modrinth.com/plugin/realinvisibility'
main: icu.suc.realinvisibility.paper.RealInvisibility
api-version: '1.21'
depend: [ packetevents ]